defmodule Humanumbers do
  def humanize(0), do: "zero"
  def humanize(1), do: "one"
  def humanize(2), do: "two"
  def humanize(3), do: "three"
  def humanize(4), do: "four"
  def humanize(5), do: "five"
  def humanize(6), do: "six"
  def humanize(7), do: "seven"
  def humanize(8), do: "eight"
  def humanize(9), do: "nine"
  def humanize(10), do: "ten"
  def humanize(11), do: "eleven"
  def humanize(12), do: "twelve"
  def humanize(13), do: "thirteen"
  def humanize(14), do: "fourteen"
  def humanize(15), do: "fifteen"
  def humanize(16), do: "sixteen"
  def humanize(17), do: "seventeen"
  def humanize(18), do: "eighteen"
  def humanize(19), do: "nineteen"
  def humanize(20), do: "twenty"
end
